### PR TITLE
ADD Windows Support

### PR DESCRIPTION
**Pull request by mastrero**
Only works in PowerShell

### CODE REVIEW

**Comment by devpolo** [comment]
Hi @mastrero,
Thank you for your contribution. That's a lot of work 😃 

It looks like it's not working on my Windows PowerShell :
- [ ] Emojis are throwing an unexpected error
- [ ] I had to add extra premission `Set-ExecutionPolicy Unrestricted`

I'll try to fix it this morning and share it with you

**Comment by mastrero** [comment]
Hi @devpolo 
I forgot to mention that Emojis do not work on bare PS terminal.

I use [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701#activetab=pivot:overviewtab) & also emojis work in VS code terminal.

**Comment by devpolo** [comment]
@mastrero what do you think?

**Comment by mastrero** [comment]
Looks great. But I feel like help Command column should be elaborated.

**Comment by devpolo** [comment]
> Looks great. But I feel like help Command column should be elaborated.

👀 What's in your mind?

**Comment by devpolo** [comment]
Ok, I roll back to this version :)

**Review by mastrero — COMMENTED** [review]
yay.. looks good

**Comment by devpolo** [comment]
Thank you very much for your contribution!
I really appreciate it.

**Pull request merged**
